# Generated by Django 5.2.11 on 2026-04-14 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagerSim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='percentage_chance',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='save',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='save',
            name='total_days',
            field=models.IntegerField(default=42, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
