# Generated by Django 5.2.11 on 2026-04-15 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projectManagerSim",
            "0002_decision_percentage_chance_alter_save_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="percentage_chance",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
