from .admin.admin_dashboard_view import *
from .admin.admin_game_content_view import *
from .admin.admin_save_list_view import *
from .admin.admin_settings_view import *
from .admin.admin_statistics_view import *
from .assign_task_view import *
from .character_selection_view import *
from .game.game_character_list_view import *
from .game.game_dashboard_view import *
from .game.game_decision_view import *
from .game.game_end_view import *
from .game.game_relationships_view import *
from .game.game_start_view import *
from .game.game_statistics_view import *
from .game.game_task_list_view import *
from .get_latest_task_view import *
from .home_view import *
from .log_in_view import *
from .log_out_view import *
from .remove_task_view import *
from .save_precheck_view import *
from .sign_up_view import *
from .start_day_view import *
from .toggle_resting_view import *
from .user.user_dashboard_view import *
from .user.user_settings_view import *
from .tour_view import *
from .previous_saves_view import *
