"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oq@lp0y^9&uifp@rp_%#jf#3m+at(%au^0q=55hk8b%j*1t1fq'

# SECURITY WARNING: don't run with debug turned on in production!
env_debug = os.environ.get('DJANGO_DEBUG', 'False').lower()

if env_debug == 'true':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['k23150452.pythonanywhere.com', 'localhost', '127.0.0.1','web-production-6784f.up.railway.app', '.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://web-production-6784f.up.railway.app',
]

# Authentication settings

# URL Anonymous users are redirected to if they try to access a view that requires login
LOGIN_URL = 'log_in'

# URL redirected to after successful login if there is no 'next' parameter in the URL
LOGIN_REDIRECT_URL = 'game_start'

# URL redirected to after loging out
LOGOUT_REDIRECT_URL = 'home'

# URL redirected to if an authenticated user tries to access pages for Anonymous users, like the home page
REDIRECT_URL_WHEN_LOGGED_IN = 'user_dashboard'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django_extensions',
    'widget_tweaks',
    'django.contrib.staticfiles',
    "polymorphic",
    'projectManagerSim'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'projectManagerSim.middleware.tour_middleware.TourMiddleware',

] # 'projectManagerSim.middleware.middleware.LoginRequiredMiddleware', 

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'projectManagerSim/templates',
            BASE_DIR / 'projectManagerSim/templates/admin',
            BASE_DIR / 'projectManagerSim/templates/game',
            BASE_DIR / 'projectManagerSim/templates/user',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Where collectstatic gathers files TO (should be gitignored)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# URL to serve static files
STATIC_URL = '/static/'

# Where your SOURCE static files live (these SHOULD be in Git)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Your app's static files
]
